### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by Lutra-Fs** [zlyfer/Material-Clock#1]
I try to use it as exe,so I chose electron to package it as exe,but there is a triangle when comes to 35s/m.on the clock.
Because I cannot submit a picture on a phone,so the screenshot will be uploaded tomorrow.

**Comment by zlyfer** [comment]
Seen, will investigate when screenshot provided.

**Comment by Lutra-Fs** [comment]
![default](https://user-images.githubusercontent.com/36790218/48966287-8f0a7800-f009-11e8-9241-16211512482e.png)
()

**Comment by zlyfer** [comment]
As far as I can tell this is most probably an issue on the side of p5js. I don't think I can do much about that.
You could try your luck at [P5JS Issues](https://github.com/processing/p5.js/issues) and ask about "arc()" issues in electron. Maybe someone there knows the answer.

I believe this issues/bug appears when using electron because [My Web Example](https://zlyfer.net/sites/visual-demonstrations/Material-Clock/) works fine on all common browsers for me.
